development:
  cloud_name: abhishek
  api_key: '294142518454137'
  api_secret: RDQDuA7nPKukdOYo6m_SJp6xGTQ
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: abhishek
  api_key: '294142518454137'
  api_secret: RDQDuA7nPKukdOYo6m_SJp6xGTQ
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: abhishek
  api_key: '294142518454137'
  api_secret: RDQDuA7nPKukdOYo6m_SJp6xGTQ
  enhance_image_tag: true
  static_image_support: false